#!/usr/bin/env python3
"""
Generate _version.py file for PyInstaller builds.
Run this before building with PyInstaller.
"""
from setuptools_scm import get_version

def generate_version_file():
    version = get_version(root=".", relative_to=__file__)

    version_file = "src/gensec/_version.py"
    with open(version_file, "w") as f:
      f.write(f'# Auto-generated by generate_version.py\n')
      f.write(f'__version__ = "{version}"\n')

    print(f"✓ Generated {version_file} with version: {version}")

if __name__ == "__main__":
    generate_version_file()