uv run gensec run examples/biaxial_column.yaml --output-dir results/biaxial_column
uv run gensec run examples/example_tee.yaml --output-dir results/example_tee
uv run gensec run examples/example_biaxial_column.yaml --output-dir results/example_biaxial_column
uv run gensec run examples/example_annulus.yaml --output-dir results/example_annulus
uv run gensec run examples/example_input.yaml --output-dir results/example_input
uv run gensec run examples/example_custom.yaml --output-dir results/example_custom
uv run gensec run examples/vcaslu_1.yaml --output-dir results/vcaslu_1
uv run gensec run examples/example_v2_1.yaml --output-dir results/example_v2_1
uv run gensec run examples/example_prestress.yaml --output-dir results/example_prestress
uv run gensec run examples/example_staged_construction.yaml --output-dir results/example_staged_construction