uv run tests\run_bulk_prestrain_validation_new.py
uv run tests\run_phase3_validation.py
uv run tests\run_phase4_yaml_validation.py
uv run tests\run_posttension_sequence_validation.py
uv run tests\run_posttension_shortening_validation.py
uv run tests\run_prestress_action_validation.py
uv run tests\run_prestress_uls_unbonded_validation.py
uv run tests\run_phase7_sls_validation.py
uv run tests\run_phase8_task1_validation.py
uv run tests\run_phase8_task2_validation.py
uv run tests\run_phase8_task3_validation.py
uv run tests\run_phase5_c5_validation.py